name: Node.js Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  eslint-check:
    name: ESLint check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.15.0]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run ESLint
      run: npx eslint .
  jest-check:
    name: Jest unit testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.15.0]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run Jest unit testing
      run: npx jest
